# -*- coding: utf-8 -*-
"""SM_ASSIGNMENT_C222.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-pJga8W0UiYlEnwlGapq0wxLiK3adASf

**Data Analysis on Football Players**
**#C222**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files 
uploaded = files.upload()

df = pd.read_csv('Football Players Stats.csv', encoding = 'ISO-8859-1')
df

df.shape

df.head()

#selecting the columns of our interest
df = df[['Player', 'Team', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s','Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR']]
df.head()

df.isnull().sum()

df = df.dropna()
df.shape

df.info()

df['Min'] = df['Min'].replace(',', '', regex = True)

df['Nation'].values[:10]

import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.figure(figsize = (8, 5))
sns.barplot(df['Nation'].value_counts()[:10].index,
           df['Nation'].value_counts()[:10].values)
plt.title('Players Nationality')
plt.xlabel('Nation')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize = (8, 5))
sns.histplot(df['Age'], kde = True)
plt.title('EPL players Age distribution')
plt.show()

df[df['Gls'] == df['Gls'].max()]

df['Goal_per_min'] = df['Gls'] / df['Min'].astype(int)
df.sort_values(by = 'Goal_per_min', ascending = False).head(10)

cards_df = df.groupby(['Team']).agg({'CrdY':'sum','CrdR':'sum'}).sort_values(by = 'CrdY', ascending = False)
cards_df.head()

plt.figure(figsize = (13, 6))
sns.barplot(cards_df.index, cards_df['CrdY'])
plt.xticks(rotation = 70)
plt.title('Yellow cards received by team')
plt.ylabel('Yellow card count')
plt.show()